### ISSUE TITLE
Project02Test Fails Arbitrarily

### ISSUE THREAD

**Issue by jrg94** [jrg94/CSE1223#4]
For whatever reason, Project02Test fails for some cases yet to be determined.

**Culprit:**
*C:\Users\Jerem\Downloads\submissions\georgeerin_191135_9834175_Project02\Project02\src\osu\cse1223\Project02.java*

```
package osu.cse1223;

import java.util.Scanner;

public class Project02 {

 public static void main(String[] args) {
  
  Scanner keyboard = new Scanner(System.in);
  System.out.println("Enter a long string: ");
  String longText = keyboard.nextLine();
  System.out.println("Enter a substring: ");
  String subText = keyboard.nextLine();
  int longTextLength = longText.length();
  System.out.println("Length of your string: " + longTextLength);
  int subTextLength = subText.length();
  System.out.println("Length of your substring: " + subTextLength);
  int subIndex = longText.indexOf(subText);
  System.out.println("Starting position of your substring in string: " + subIndex);
  String before = longText.substring(0,(subIndex-1));
  System.out.println("String before your substring: " + before);
  int subEndIndex = subIndex + subTextLength;
  String after = longText.substring(subEndIndex);
  System.out.println("String after your substring: " + after);
  System.out.println("Enter a position between 0 and " + (longTextLength - 1) + ": ");
  int position = keyboard.nextInt();
  char random = longText.charAt(position);
  System.out.println("The character at position " + position + " is " + random);
  System.out.println("Enter a replacement string: ");
  Scanner keyboard2 = new Scanner(System.in);
  String userInput = keyboard2.nextLine();
  String replaced = longText.replace(subText, userInput);
  System.out.println("Your new string is: " + replaced);
}}
```

**Test file:** 
*C:\Users\Jerem\Downloads\submissions\Project02Test.java*

**Comment by jrg94** [comment]
When executed, this file seems to run exactly as expected.

**Comment by jrg94** [comment]
I also have various Dr. Java errors:

```
java.lang.NullPointerException: peer
	at sun.awt.windows.WInputMethod.openCandidateWindow(Native Method)
	at sun.awt.windows.WInputMethod.access$400(Unknown Source)
	at sun.awt.windows.WInputMethod$1.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)


System Properties:
DrJava Version drjava-20160913-225446
DrJava Build Time 20160913-225446

drjava.debug.port = 58607
java.runtime.name = Java(TM) SE Runtime Environment
sun.boot.library.path = C:\Program Files\Java\jre1.8.0_161\bin
java.vm.version = 25.161-b12
java.vm.vendor = Oracle Corporation
java.vendor.url = http://java.oracle.com/
path.separator = ;
java.vm.name = Java HotSpot(TM) 64-Bit Server VM
file.encoding.pkg = sun.io
user.country = US
user.script = 
sun.java.launcher = SUN_STANDARD
sun.os.patch.level = 
java.vm.specification.name = Java Virtual Machine Specification
user.dir = <anonymized user.home>\Downloads
java.runtime.version = 1.8.0_161-b12
java.awt.graphicsenv = sun.awt.Win32GraphicsEnvironment
java.endorsed.dirs = C:\Program Files\Java\jre1.8.0_161\lib\endorsed
os.arch = amd64
java.io.tmpdir = <anonymized user.home>\AppData\Local\Temp\
line.separator = "\u000d\u000a"
java.vm.specification.vendor = Oracle Corporation
user.variant = 
os.name = Windows 10
sun.jnu.encoding = Cp1252
java.library.path = C:\Program Files\Java\jre1.8.0_161\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.2\libnvvp;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\GYB\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;<anonymized user.home>\AppData\Local\Microsoft\WindowsApps;<anonymized user.home>\AppData\Local\GitHubDesktop\bin;<anonymized user.home>\AppData\Local\atom\bin;C:\Program Files\Nim\nim-0.18.0_x64\nim-0.18.0\bin;<anonymized user.home>\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Docker Toolbox;<anonymized user.home>\AppData\Local\Programs\Python\Python36-32\Scripts;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Scripts;C:\MinGW\bin;;.
sun.awt.enableExtraMouseButtons = true
java.specification.name = Java Platform API Specification
java.class.version = 52.0
sun.management.compiler = HotSpot 64-Bit Tiered Compilers
os.version = 10.0
user.home = <anonymized user.home>
user.timezone = America/New_York
java.awt.printerjob = sun.awt.windows.WPrinterJob
file.encoding = Cp1252
java.specification.version = 1.8
java.class.path = <anonymized user.home>\Downloads\drjava-beta-20160913-225446.jar
user.name = <anonymized user.name>
java.vm.specification.version = 1.8
sun.java.command = <anonymized user.home>\Downloads\drjava-beta-20160913-225446.jar
java.home = C:\Program Files\Java\jre1.8.0_161
sun.arch.data.model = 64
user.language = en
java.specification.vendor = Oracle Corporation
awt.toolkit = sun.awt.windows.WToolkit
java.vm.info = mixed mode
java.version = 1.8.0_161
java.ext.dirs = C:\Program Files\Java\jre1.8.0_161\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
sun.boot.class.path = C:\Program Files\Java\jre1.8.0_161\lib\resources.jar;C:\Program Files\Java\jre1.8.0_161\lib\rt.jar;C:\Program Files\Java\jre1.8.0_161\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_161\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_161\lib\jce.jar;C:\Program Files\Java\jre1.8.0_161\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_161\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_161\classes
java.vendor = Oracle Corporation
file.separator = \
java.vendor.url.bug = http://bugreport.sun.com/bugreport/
sun.io.unicode.encoding = UnicodeLittle
sun.cpu.endian = little
java.rmi.server.hostname = 127.0.0.1
sun.desktop = windows
sun.cpu.isalist = amd64

DrJava configuration file
In resource bundle edu.rice.cs.drjava.config.options:
	nothing

In shadowed configuration:
lineenum.enabled = true
key.delete.next = [shift DELETE]
key.delete.previous = [shift BACK_SPACE]
recent.files = [C:\\Users\\Jerem\\Downloads\\submissions\\georgeerin_191135_9834175_Project02\\Project02\\src\\osu\\cse1223\\Project02.java,C:\\Users\\Jerem\\Downloads\\submissions\\forsternatalie_182126_9832772_Project02\\Project02\\src\\Project02.java,C:\\Users\\Jerem\\Downloads\\submissions\\ehaalex_200924_9846322_Project02_Eha\\ClosedLab01\\src\\osu\\cse1223\\Project02.java,C:\\Users\\Jerem\\Downloads\\submissions\\dimmickalex_182732_9845503_Project02\\Project02\\src\\osu\\cse1223\\Project02.java,C:\\Users\\Jerem\\Downloads\\submissions\\Project02Test.java]
window.height = 1448
window.width = 1296
window.x = -8
window.y = 0
last.dir = C:\\Users\\Jerem\\Downloads\\submissions\\georgeerin_191135_9834175_Project02\\Project02\\src\\osu\\cse1223
last.interactions.dir = C:\\Users\\Jerem\\Downloads\\submissions
tabbedpanes.state = 960 540 700 400
new.version.notification.last = 1536190675206
file.ext.registration = never


Used memory: about 68.49 megabytes
Free memory: about 124.51 megabytes
Total memory: about 193 megabytes
Total memory can expand to: about 3.53 gigabytes

Number of processors/cores: 4

Compiler Discovery Log:
```

**Comment by jrg94** [comment]
Another that fails:

```
package osu.cse1223;

import java.util.Scanner;

public class Project02 {

 public static void main(String[] args) {
  Scanner keyboard = new Scanner(System.in);
  System.out.print("Enter a long string: ");
  String word = keyboard.nextLine();
  System.out.print("Enter a substring: ");
  String word1 = keyboard.nextLine();
  System.out.println("Length of your string: " + word.length());
  System.out.println("Length of your substring: " + word1.length());
  System.out.println("Starting position of your substring in string: " + word.indexOf(word1));
  System.out.println("String before your substring: " + word.substring(0,word.indexOf(word1)));
  System.out.println("String after your substring: " + word.substring(word.indexOf(word1)+word1.length()));
  System.out.print("Enter a position between 0 and 43: ");
  int number = keyboard.nextInt();
  System.out.println("The character at position " + number + " is " + word.charAt(number));
  System.out.print("Enter a replacement string: ");
  Scanner name = new Scanner(System.in);
  String word2 = name.nextLine();
  System.out.println("Your new string is: " + word.replace(word1, word2));
 }
}
```

**Comment by jrg94** [comment]
Found another one:

```
package project02;

import java.util.Scanner;

public class Project02 {
 
 public static void main(String[] args) {
  Scanner keyboard = new Scanner(System.in);
  System.out.print("Enter a long string: ");
  String Long = keyboard.nextLine();
  System.out.print("Enter a substring: ");
  String Sub = keyboard.nextLine();
  int Longlen = Long.length();
  int Sublen = Sub.length();
  System.out.println("Length of your string: " +Longlen);
  System.out.println("Length of your substring: " +Sublen);
  int subposition = Long.indexOf(Sub);
  System.out.println("Starting position of your substring in string: " +subposition);
  System.out.println("String before your substring: " +Long.substring(0,subposition));
  System.out.println("String after your substring: " +Long.substring(subposition+Sublen,Longlen));
  int truelen = Longlen-1;
  System.out.print("Enter a position between 0 and " +truelen+ ": ");
  String randomposition = keyboard.nextLine();
  int val = Integer.parseInt(randomposition);
  char letter = Long.charAt(val);
  System.out.println("The character at position " +randomposition + " is " +letter);
  System.out.println("Enter a replacement string: ");
  String replacement = keyboard.nextLine();
  System.out.println("Your new string is: " +Long.substring(0,subposition)+replacement+Long.substring(subposition+Sublen,Longlen));
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
 } 
}
```

**Comment by jrg94** [comment]
Yet another failing solution:

```
package cse1223;

import java.util.Scanner;

public class Project02 {

 public static void main(String[] args) {
  // TODO Auto-generated method stub
  Scanner keyboard = new Scanner(System.in);
  System.out.print("Enter a long string: ");
  String a = keyboard.nextLine();
  System.out.print("Enter a substring: ");
  String b = keyboard.nextLine();
  int lengtha = a.length();
  int lengthb = b.length();
  System.out.println("Length of your string: " + lengtha);
  System.out.println("Length of your substring: " + lengthb);
  int starting = a.indexOf(b);
  System.out.println("Starting position of your substring in string: " + starting);
  String before = a.substring(0,starting);
  System.out.println("String before your substring: " + before);
  String after = a.substring(starting+lengthb);
  System.out.println("String after your substring: " + after);
  System.out.print("Enter a position between 0 and 43: ");
  int position = keyboard.nextInt();
  char positiona = a.charAt(position);
  System.out.println("The character at position " + position + " is " + positiona);
  keyboard.nextLine();
  System.out.print("Enter a replacement string: ");
  String replacement = keyboard.nextLine();
  System.out.println("Your new string is: " + before + replacement + after);
   }


 }
```

**Comment by jrg94** [comment]
I think these are all package errors.
